// Mock data para desarrollo y pruebas
import { Technician, WorkOrder, LoginResponse } from './api';

// Usuarios mock
export const mockUsers = {
  supervisor_test: {
    password: 'password123',
    user: {
      id: 'sup-001',
      username: 'supervisor_test',
      role: 'supervisor',
    },
  },
  admin_demo: {
    password: 'admin123',
    user: {
      id: 'adm-001',
      username: 'admin_demo',
      role: 'admin',
    },
  },
  'admin@telconova.com': {
    password: 'admin123',
    user: {
      id: 'adm-002',
      username: 'admin@telconova.com',
      role: 'admin',
    },
  },
};

// Técnicos mock
export const mockTechnicians: Technician[] = [
  {
    id: 'tech-001',
    name: 'Carlos Rodríguez',
    email: 'carlos.rodriguez@telconova.com',
    phone: '+57 300 123 4567',
    specialty: 'Fibra Óptica',
    zone: 'Norte',
    availability: 'available',
    currentLoad: 0,
    certifications: ['FTTH', 'Fusión de Fibra', 'GPON'],
  },
  {
    id: 'tech-002',
    name: 'Ana María González',
    email: 'ana.gonzalez@telconova.com',
    phone: '+57 301 234 5678',
    specialty: 'Redes Inalámbricas',
    zone: 'Sur',
    availability: 'available',
    currentLoad: 1,
    certifications: ['WiFi 6', 'Mikrotik', 'Ubiquiti'],
  },
  {
    id: 'tech-003',
    name: 'Miguel Ángel Pérez',
    email: 'miguel.perez@telconova.com',
    phone: '+57 302 345 6789',
    specialty: 'Cableado Estructurado',
    zone: 'Centro',
    availability: 'busy',
    currentLoad: 3,
    certifications: ['Cat6A', 'Cat7', 'Certificación Fluke'],
  },
  {
    id: 'tech-004',
    name: 'Laura Martínez',
    email: 'laura.martinez@telconova.com',
    phone: '+57 303 456 7890',
    specialty: 'Fibra Óptica',
    zone: 'Norte',
    availability: 'available',
    currentLoad: 1,
    certifications: ['FTTH', 'OTDR', 'Splicing'],
  },
  {
    id: 'tech-005',
    name: 'Juan David Silva',
    email: 'juan.silva@telconova.com',
    phone: '+57 304 567 8901',
    specialty: 'Telefonía IP',
    zone: 'Este',
    availability: 'available',
    currentLoad: 2,
    certifications: ['VoIP', 'Asterisk', 'SIP Trunking'],
  },
  {
    id: 'tech-006',
    name: 'Patricia Ramírez',
    email: 'patricia.ramirez@telconova.com',
    phone: '+57 305 678 9012',
    specialty: 'Redes Inalámbricas',
    zone: 'Oeste',
    availability: 'busy',
    currentLoad: 2,
    certifications: ['WiFi 6E', 'Site Survey', 'Ruckus'],
  },
  {
    id: 'tech-007',
    name: 'Roberto Gómez',
    email: 'roberto.gomez@telconova.com',
    phone: '+57 306 789 0123',
    specialty: 'Cableado Estructurado',
    zone: 'Sur',
    availability: 'offline',
    currentLoad: 0,
    certifications: ['TIA-568', 'Data Center', 'Panduit'],
  },
  {
    id: 'tech-008',
    name: 'Diana López',
    email: 'diana.lopez@telconova.com',
    phone: '+57 307 890 1234',
    specialty: 'Fibra Óptica',
    zone: 'Centro',
    availability: 'available',
    currentLoad: 0,
    certifications: ['FTTH', 'FTTx', 'PON'],
  },
];

// Órdenes de trabajo mock
export const mockWorkOrders: WorkOrder[] = [
  {
    id: 'WO-2025-001',
    clientName: 'Edificio Empresarial Torre Norte',
    address: 'Calle 100 #15-20, Bogotá',
    zone: 'Norte',
    priority: 'high',
    specialty: 'Fibra Óptica',
    description: 'Instalación de enlace de fibra óptica de 1Gbps para 50 usuarios. Requiere fusión de fibra y certificación de enlace.',
    status: 'pending',
    createdAt: '2025-01-27T08:00:00Z',
  },
  {
    id: 'WO-2025-002',
    clientName: 'Hotel Plaza Real',
    address: 'Carrera 7 #45-30, Bogotá',
    zone: 'Centro',
    priority: 'high',
    specialty: 'Redes Inalámbricas',
    description: 'Ampliación de red WiFi para 100 habitaciones. Instalación de 15 access points WiFi 6.',
    status: 'pending',
    createdAt: '2025-01-27T09:15:00Z',
  },
  {
    id: 'WO-2025-003',
    clientName: 'Centro Comercial Sur Plaza',
    address: 'Avenida Américas #68-50, Bogotá',
    zone: 'Sur',
    priority: 'medium',
    specialty: 'Cableado Estructurado',
    description: 'Instalación de cableado Cat6A para 80 puntos de red en locales comerciales.',
    status: 'assigned',
    assignedTechnicianId: 'tech-003',
    assignedAt: '2025-01-27T10:30:00Z',
    assignedBy: 'supervisor_test',
    createdAt: '2025-01-26T14:00:00Z',
  },
  {
    id: 'WO-2025-004',
    clientName: 'Clínica Santa Fe',
    address: 'Calle 26 #80-15, Bogotá',
    zone: 'Oeste',
    priority: 'high',
    specialty: 'Telefonía IP',
    description: 'Migración de sistema telefónico análogo a VoIP. 120 extensiones.',
    status: 'pending',
    createdAt: '2025-01-27T07:30:00Z',
  },
  {
    id: 'WO-2025-005',
    clientName: 'Universidad Tecnológica',
    address: 'Carrera 50 #127-20, Bogotá',
    zone: 'Norte',
    priority: 'medium',
    specialty: 'Fibra Óptica',
    description: 'Mantenimiento preventivo de red de fibra óptica del campus. Medición OTDR y limpieza de conectores.',
    status: 'assigned',
    assignedTechnicianId: 'tech-004',
    assignedAt: '2025-01-27T11:00:00Z',
    assignedBy: 'supervisor_test',
    createdAt: '2025-01-25T10:00:00Z',
  },
  {
    id: 'WO-2025-006',
    clientName: 'Parque Industrial Este',
    address: 'Autopista Norte Km 5, Bogotá',
    zone: 'Este',
    priority: 'low',
    specialty: 'Redes Inalámbricas',
    description: 'Instalación de red WiFi en zona de parqueaderos. 8 access points exteriores.',
    status: 'in_progress',
    assignedTechnicianId: 'tech-002',
    assignedAt: '2025-01-26T15:00:00Z',
    assignedBy: 'automatic',
    createdAt: '2025-01-24T16:00:00Z',
  },
  {
    id: 'WO-2025-007',
    clientName: 'Residencial Los Pinos',
    address: 'Calle 170 #25-40, Bogotá',
    zone: 'Norte',
    priority: 'low',
    specialty: 'Fibra Óptica',
    description: 'Servicio de internet residencial 200Mbps. Instalación FTTH para 5 apartamentos.',
    status: 'pending',
    createdAt: '2025-01-27T11:30:00Z',
  },
  {
    id: 'WO-2025-008',
    clientName: 'Oficinas Central Bank',
    address: 'Carrera 15 #90-10, Bogotá',
    zone: 'Centro',
    priority: 'high',
    specialty: 'Cableado Estructurado',
    description: 'Urgente: Reemplazo de switches principales y recableado de patch panels. 150 puntos.',
    status: 'assigned',
    assignedTechnicianId: 'tech-003',
    assignedAt: '2025-01-27T08:45:00Z',
    assignedBy: 'supervisor_test',
    createdAt: '2025-01-27T08:00:00Z',
  },
  {
    id: 'WO-2025-009',
    clientName: 'Restaurant La Estancia',
    address: 'Zona T, Calle 82 #12-50, Bogotá',
    zone: 'Norte',
    priority: 'medium',
    specialty: 'Redes Inalámbricas',
    description: 'Actualización de red WiFi para clientes. 5 access points con portal cautivo.',
    status: 'completed',
    assignedTechnicianId: 'tech-001',
    assignedAt: '2025-01-25T09:00:00Z',
    assignedBy: 'supervisor_test',
    createdAt: '2025-01-24T12:00:00Z',
  },
  {
    id: 'WO-2025-010',
    clientName: 'Colegio San Marcos',
    address: 'Calle 140 #10-15, Bogotá',
    zone: 'Norte',
    priority: 'medium',
    specialty: 'Telefonía IP',
    description: 'Instalación de sistema de intercomunicación IP para 30 aulas.',
    status: 'completed',
    assignedTechnicianId: 'tech-005',
    assignedAt: '2025-01-23T10:00:00Z',
    assignedBy: 'automatic',
    createdAt: '2025-01-22T14:00:00Z',
  },
];

// Simular delay de red
export const simulateDelay = (ms: number = 500) => 
  new Promise(resolve => setTimeout(resolve, ms));
